### PR TITLE
fix(swift): region support

### LINKED ISSUE #295: [BUG] Swift snapstore does not natively support regions
**Describe the bug:**
I use Swift snapstore and I have multiple Openstack regions in my tenant. I'm not able to set a region to the Swift snapstore config.

**Expected behavior:**
Support `OS_REGION_NAME` as  OS_USERNAME, OS_PASSWORD, OS_AUTH_URL, OS_TENANT_ID and OS_DOMAIN_ID, OS_CLOUD is.

**How To Reproduce (as minimally and precisely as possible):**
Try to perform backup on a different 

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID : -
 - Etcd-backup-restore version/commit ID: b0847ed07ae525655be1ab7ed371bec2823de7be
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: Swift 

**Anything else we need to know?**:
https://github.com/gophercloud/gophercloud/blob/master/README.md#provision-a-server

### PR DESCRIPTION
**Pull request by miton18**
Signed-off-by: Rémi Collignon <remi+github@collignon-ducret.fr>

**What this PR does / why we need it**:
Handle regions in Swift snapstore

**Which issue(s) this PR fixes**:
Fixes #295 

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @miton18 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by amshuman-kr — APPROVED** [review]
Thanks for the contribution @miton18! LGTM

**Review by shreyas-s-rao — CHANGES_REQUESTED** [review]
@miton18 Thanks for your PR. While it's ok to add `OS_REGION_NAME` to create the client, we also need to keep this backward compatible. So please change the code such that you pass the `Region` field to `NewObjectStorageV1()` only if the environment variable is available. If not, then call `NewObjectStorageV1()` without the Region field in the `EndpointOps`.

Also, please add `OS_REGION_NAME` (or `regionName`) [here](https://github.com/gardener/etcd-backup-restore/blob/b0847ed07ae525655be1ab7ed371bec2823de7be/chart/etcd-backup-restore/values.yaml#L86), [here](https://github.com/gardener/etcd-backup-restore/blob/b0847ed07ae525655be1ab7ed371bec2823de7be/chart/etcd-backup-restore/templates/etcd-backup-secret.yaml#L27), [here](https://github.com/gardener/etcd-backup-restore/blob/b0847ed07ae525655be1ab7ed371bec2823de7be/chart/etcd-backup-restore/templates/etcd-statefulset.yaml#L199) and [here](https://github.com/gardener/etcd-backup-restore/blob/master/doc/usage/getting_started.md#L19), and please make it an optional field. 

At the same time, please also raise a PR on https://github.com/gardener/etcd-druid/ to add this functionality to the etcd charts there, as `etcd-druid` is the primary operator meant to deploy etcd-backup-restore. In that PR, you will have to make similar changes [here](https://github.com/gardener/etcd-druid/blob/8307a62ad71ec0de3bf78de6d0e2bbc07700042c/charts/etcd/templates/etcd-statefulset.yaml#L229) and [here](https://github.com/gardener/etcd-druid/blob/8307a62ad71ec0de3bf78de6d0e2bbc07700042c/controllers/etcd_controller_test.go#L1333). Hint: use `IgnoreMissing` option in the test spec to make this env variable optional.

**Comment by miton18** [comment]
>So please change the code such that you pass the `Region` field to `NewObjectStorageV1()` only if the environment variable is available. If not, then call `NewObjectStorageV1()` without the Region field in the `EndpointOps`.

The current behaviour of `Getenv()` is to return an empty string if not set, this is the current default value set for `EndpointOpts.Region`, when nothing is given as value.

**Review by shreyas-s-rao — APPROVED** [review]
@miton18 Thanks for making the changes. Apologies for the delay in review. LGTM

**Comment by shreyas-s-rao** [comment]
🗒️  Error in integration test is due to python issue already fixed [here](https://github.com/gardener/etcd-backup-restore/commit/9f1fb9ca3973d07c81d96b530e1298cb7b25d41f), and this PR would not affect the integration test. So going ahead and merging.

**Pull request merged**
