### PR TITLE
Fix AWS_FORCE_PATH_STYLE env parsing

### LINKED ISSUE #461: [BUG] AWS_FORCE_PATH_STYLE env is ignored
**Describe the bug:**
AWS_FORCE_PATH_STYLE env variable is ignored
**Expected behavior:**
AWS_FORCE_PATH_STYLE env variable should set S3ForcePathStyle in s3 client
**How To Reproduce (as minimally and precisely as possible):**
Set AWS_FORCE_PATH_STYLE on v0.15.1

### PR DESCRIPTION
**Pull request by mixitgit**
Signed-off-by: Mikhail Sidorov <sidorov.ml99@gmail.com>

**What this PR does / why we need it**:
Fixes AWS_FORCE_PATH_STYLE env parsing
**Which issue(s) this PR fixes**:
Fixes #461

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @mixitgit for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by ishan16696** [comment]
Hi @mixitgit,
Can you also open a similar PR for branch `rel-v0.15` ?

**Comment by mixitgit** [comment]
@ishan16696 sure

**Comment by mixitgit** [comment]
@ishan16696 Opened #464

**Pull request merged**
