### PR TITLE
Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by aaronfern**
**What this PR does / why we need it**:
Updated a few dependencies in light of discovered vulnerabilities highlighted by dependabot

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
For reference 
1. https://github.com/advisories/GHSA-c3xm-pvg7-gh7r
2. https://github.com/advisories/GHSA-w73w-5m7g-f7qc
3. https://github.com/advisories/GHSA-c72p-9xmj-rx3w

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by timuthy** [comment]
@aaronfern / @ishan16696 can we merge this PR?

**Comment by aaronfern** [comment]
I would suggest running the unit/integration tests again before we merge this PR as it was filed some time back
/second-opinion @ishan16696 @abdasgupta

**Comment by ishan16696** [comment]
> I would suggest running the unit/integration tests again before we merge this PR as it was filed some time back.

yes, make sense .. I already opened a PR to update credentials on `cc-config`.

**Review by timuthy — APPROVED** [review]
Thanks 🙂

**Pull request merged**
