### PR TITLE
Fix memory leak during full snapshot

### PR DESCRIPTION
**Pull request by databus23**
This fixes a memory/goroutine leak that caused several gouroutines and memory to leak every time a full snapshot was execucted because the old watch was never closed and continued to receive updates that were not processed.

From the etcd client godocs:
> The context "ctx" MUST be canceled, as soon as watcher is no longer being used, to release the associated resources.

https://github.com/etcd-io/etcd/blob/4cd0bf8ea846a0d158761d55899f631eb2a423cf/clientv3/watch.go#L52-L53

**What this PR does / why we need it**:
It fixes a serious memory leak

**Which issue(s) this PR fixes**:
Not sure maybe #102

**Special notes for your reviewer**:
From Converged Cloud Enterprise Edition with ❤️ 

**Release note**:

```noteworthy operator
Fixed memory/goroutine leak: close previous Etcd watches
```

### CODE REVIEW

**Comment by databus23** [comment]
I just found #99 which also talks about this memory leak but the PR seems to be changing a lot more than just this memory leak.
/cc @swapnilgm

**Comment by amshuman-kr** [comment]
@databus23 Thanks a lot. This seems to have [nailed it](https://github.com/gardener/etcd-backup-restore/issues/102#issuecomment-463679537). ❤️

@swapnilgm Can we take this up for validation and merge?

**Comment by databus23** [comment]
@amshuman-kr Thanks for responding so quickly. I would love a quick 0.4.2 release. we have 30 instances of the latest (0.4.1) backup sidecar constantly crashing (~6h) because of this memory leak.

**Comment by amshuman-kr** [comment]
@databus23 We will take the release on priority tomorrow.

**Comment by databus23** [comment]
a little follow up. I'm still pretty satisfied with the results for far:
image

The graph shows the last 2 days of a crashing backup sidecar. The newest two graphs are with the patch applied.

**Comment by amshuman-kr** [comment]
@databus23 Thanks for the follow up.

I verified the combination of full and delta snapshot too. The memory leaks seems to be resolved in that scenario too. But full snapshot is still taking up [more memory](https://github.com/gardener/etcd-backup-restore/issues/102#issuecomment-463905222) than I think it should. But it is not a memory leak anymore. So, it is not a blocker for a quick release.

**Comment by swapnilgm** [comment]
@amshuman-kr Thanks you for comparing results and verifying it.

**Pull request merged**
