### PR TITLE
Mock ETCD clientv3 for unit tests.

### PR DESCRIPTION
**Pull request by amshuman-kr**
**What this PR does / why we need it**:

Generated mock client for ETCD clientv3 to be used in unit tests for multi-node scenarions like #321, #322 etc.

Some of the specific client interfaces (like `Cluster`, `Maintenance` etc.) do not support the [`Close` function](https://github.com/etcd-io/etcd/blob/a4a82cc98290139f95ae8d2566bdc09948123bdb/client/v3/cluster.go#L35-L53).
However, the [connection needs to be closed](https://github.com/etcd-io/etcd/blob/main/client/v3/client.go#L152) (say, by [closing the `Client` object](https://github.com/etcd-io/etcd/blob/a4a82cc98290139f95ae8d2566bdc09948123bdb/client/v3/client.go#L143-L155)).

To simplify creation and closing the specific ETCD client objects without referring to the `Client` type directly, I have introduced new interfaces (like `ClusterCloser`, `MaintenanceCloser` etc.) which supports both the corresponding ETCD client interface as well as `io.Closer`.

And to put it all together, I have introduced the `Factory` interface which allows direct construction of the specific ETCD client interfaces allowing the use of _proper_ ETCD clients based on `EtcdConnectionConfig` as well as mock clients in unit tests.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
To be merged after the [release v0.13.0](https://github.com/gardener/etcd-backup-restore/milestone/34) has been made.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by ishan16696 — APPROVED** [review]
Thanks @amshuman-kr. LGTM!!

**Comment by amshuman-kr** [comment]
[Fixed the package name](https://github.com/gardener/etcd-backup-restore/compare/ca8cf6e134dbc46b98f8a571d4565d1861d2d009..6ff7725d1ac481e797b877ecefeb5eb220924d76) in the files [here](https://github.com/gardener/etcd-backup-restore/pull/374#event-5231622643).

**Comment by amshuman-kr** [comment]
I have [refactored the mock clients](https://github.com/gardener/etcd-backup-restore/compare/6ff7725d1ac481e797b877ecefeb5eb220924d76..cee1cd2be8e82f75177a4051099b276074a7b50e) to work around on some constraints in ETCD `client/v3`. Please see [above](https://github.com/gardener/etcd-backup-restore/pull/374#issue-714102040) for more details.

**Comment by amshuman-kr** [comment]
[Fixed](https://github.com/gardener/etcd-backup-restore/pull/374#event-5260601013) the failing checks.

**Pull request merged**
