### PR TITLE
Fix etcd image for tests

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>

**What this PR does / why we need it**:
This PR fixes failing TM tests due to etcd version mismatch.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by shreyas-s-rao** [comment]
@amshuman-kr the `tm_test` CI step still fails in this PR. It would work once merged into master. PTAL.

**Review by amshuman-kr — APPROVED** [review]
LGTM. However, I am unable to run performance regression test because [`go get`](https://github.com/gardener/etcd-backup-restore/blob/master/test/perf/regression/resources/loadtest/configmap.yaml#L22) is no longer working for etcd benchmark due to https://github.com/etcd-io/etcd/issues/12124#issuecomment-660418135. Considering that the issue on etcd has been open now for 4 months should we go ahead and merge this PR already?

**Comment by amshuman-kr** [comment]
Tangent: I have created https://github.com/gardener/etcd-backup-restore/issues/281 to track the movement of performance regression test to test machinery integration tests.

**Comment by shreyas-s-rao** [comment]
@amshuman-kr Yes, we can address the perf regression tests in a separate PR, where we integrate it with the TM tests. Merging this PR now.

**Pull request merged**
