### PR TITLE
Handle TLS enable case to delegate the out-of-sync snapshot request to backup-restore leader.

### LINKED ISSUE #516: [BUG] Leader delegation does not work with self-singed certificate
**Describe the bug:**
Etcd-Backup-Restore proxys certain requests related to the `snapshotter` to the etcd leader in case of a multi-node cluster. This procedure does not work if `TLS` is enabled via `--server-cert` and `--server-key` and the certificate is not signed by a commonly trusted CA.

The following error (405) is received when the command is executed in a `follower` pod:

```
bash-5.1# curl -k -v -s curl https://etcd-main-local:8080/snapshot/latest

* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 405 
< content-security-policy: default-src 'self'
< strict-transport-security: max-age=31536000
< content-length: 0
< date: Thu, 04 Aug 2022 14:26:05 GMT
```

Pod logs:

```
time="2022-08-04T14:21:58Z" level=warning msg="Unable to check backup leader health: Get \"https://etcd-main-2.etcd-main-peer.shoot--local--local.svc:8080/healthz\": x509: certificate signed by unknown authority" actor=backup-restore-server
```

**Expected behavior:**
The proxied request should succeed.

**How To Reproduce (as minimally and precisely as possible):**
* Create or use a server certificated signed by a custom CA (not commonly trusted).
* Create a multi-node etcd cluster with TLS enabled for Backup-Restore `--server-cert`, `--server-key`.
* Execute `curl -k -v -s curl https://localhost:8080/snapshot/latest` on `follower`.

**Environment (please complete the following information):**
 - Etcd-backup-restore version/commit ID: v0.19.0 and earlier.

### PR DESCRIPTION
**Pull request by ishan16696**
**What this PR does / why we need it**:
This PR handles the TLS enable case to delegate the http request from backup-restore follower to backup-restore leader to take out-of-sync full/delta snapshot.

**Which issue(s) this PR fixes**:
Fixes #516

**Special notes for your reviewer**:

**Release note**:
```fixbug operator
Fix a bug in handling of TLS enable case to delegate the out-of-sync snapshot request to backup-restore leader.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
I have tested this PR on dev landscape. PR is ready for review now.

**Comment by ishan16696** [comment]
/duplicate https://github.tools.sap/kubernetes-live/issues-live/issues/2159

**Review by aaronfern — APPROVED** [review]
/lgtm

**Pull request merged**
