### PR TITLE
Fixes copy operation for Swift snapstore

### PR DESCRIPTION
**Pull request by plkokanov**
**What this PR does / why we need it**:
Fixes the retrieval of credentials when using the copy operation with the `Swift` snapstore.

Without this fix we get the following error when trying to copy backups:
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.

time="2022-05-06T10:29:51Z" level=info msg="etcd-backup-restore Version: v0.15.2"
time="2022-05-06T10:29:51Z" level=info msg="Git SHA: c9b5c3d0"
time="2022-05-06T10:29:51Z" level=info msg="Go Version: go1.17.9"
time="2022-05-06T10:29:51Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-05-06T10:29:51Z" level=fatal msg="Could not get source and destination snapstores: could not get source snapstore: Missing input for argument [auth_url]"
```

This is because the `getClientOpts` function was exiting too soon if `isSource==true` and was never trying to read the file containing the source store credentials. 

I've added the following code for backwards compatibility:
```
return &clientconfig.ClientOpts{
	EnvPrefix: envPrefixSource,
}, nil
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fixed retrieval of credentials during copy operation for backups stored in Swift snapstore.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
> This is because the getClientOpts function was exiting too soon if isSource==true and was never trying to read the file containing the source store credentials.

yes, I also noticed this when I was working on the secret rotation PR and  wondered why you guys are reading secret this way when `isSource=true`, sorry I forgot to inform you.

```
if isSource {
		return &clientconfig.ClientOpts{
			EnvPrefix: envPrefixSource,
		}, nil
}
```

**Comment by ishan16696** [comment]
>Could we also cherry pick this for a hotfix?

ok, do you want a hotfix release for backup-restore ?

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by plkokanov** [comment]
Hey, @ishan16696 I see that this has not been cherry picked on 0.16.0 release which has the same problem. Can we cherry pick it there as well asap?

**Pull request merged**
