### PR TITLE
Queries the actual store to fetch latest snapshot while serving the URL endpoint.

### PR DESCRIPTION
**Pull request by abdasgupta**
**What this PR does / why we need it**:
Currently, if someone queries `/snapshot/latest` endpoint in backup-restore server,  latest snapshots are served from whatever is stored in the already running snapshotter. But, ideally, the snapshots should be fetched from the actual backend store and then serve to the end users. This PR fetches the latest snapshots from actual store when an end user executes `/snapshot/latest` endpoint.

One use case of this PR is e2e tests for compaction. Full snapshots are stored in same storage by both the snapshotter and compactor. Currently, `/snapshot/latest` endpoint serves the latest snapshots from the details stored in snapshotter. While snapshotter has the information about what latest snapshots are pushed by itself, it does not have the information about the full snapshots pushed by compactor which runs separately. So, in e2e test for compaction, if we want to check the latest snapshots through this endpoint after a compaction job, this endpoint provides stale data about full snapshot as it only has the info about full snapshots pushed by the snapshotter.

**Which issue(s) this PR fixes**:
Fixes partial https://github.com/gardener/etcd-druid/issues/704

**Special notes for your reviewer**:

**Release note**:

```improvement user
The snapshots are fetched from the actual backend store when queried for latest snapshots on `/snapshot/latest` endpoint.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
Hi @abdasgupta ,
Can you please provide the context for this PR, where you want to use this endpoint: `/snapshot/latest` ? 
As I have never seen any usecases of this `/snapshot/latest` endpoint.
I'm asking this because in multi-node context only backup-restore should respond to this REST request, please refer to this issue: https://github.com/gardener/etcd-backup-restore/issues/354 for details. I worked on this issue long back. I solved it for endpoint `/snapshot/delta` and `/snapshot/full`, as `/snapshot/latest` endpoint nobody used, may be I have left this endpoint.

**Comment by ishan16696** [comment]
> I solved it for endpoint `/snapshot/delta` and `/snapshot/full`, as `/snapshot/latest` endpoint nobody used, may be I have left this endpoint.

ok, I found out this functionality is already there for endpoint: `/snapshot/latest` endpoint, sorry for the confusion
https://github.com/gardener/etcd-backup-restore/blob/ae1c95c8ba59d7134a3ac0b473b8f983716cfc3d/pkg/server/httpAPI.go#L364-L372

**Comment by ishan16696** [comment]
>  But, ideally, the snapshots should be fetched from the actual backend store and then serve to the end users. This PR fetches the latest snapshots from actual store when an end user executes /snapshot/latest endpoint.

but why it should be fetched from snapstore as backup-restore leader already have this information as it is taking the snapshot, so why use that rather then go to snapstore and list the snapshots ? Have you seen any weird behaviour like when `/latest` doesn't give latest snapshot information ?

**Comment by abdasgupta** [comment]
> > But, ideally, the snapshots should be fetched from the actual backend store and then serve to the end users. This PR fetches the latest snapshots from actual store when an end user executes /snapshot/latest endpoint.
> 
> but why it should be fetched from snapstore as backup-restore leader already have this information as it is taking the snapshot, so why not use that rather then go to snapstore and list the snapshots ? Have you seen any weird behaviour like when `/latest` doesn't give latest snapshot information ?

Yes. I have seen weird behaviour while developing the e2e tests for compaction. Ideally, a URL endpoint should always fetch data from actual backend, not from any cache or something. Full snapshots are stored in same storage by both the snapshotter and compactor. While snapshotter has the information about what latest snapshots are pushed by itself, it does not have the information about the full snapshots pushed by compactor which runs separately. So, in e2e test for compaction, if we want to check the latest snapshots  through this endpoint after a compaction job, this endpoint provides stale data about full snapshot as it only have the info about full snapshots pushed by the snapshotter.

**Comment by ishan16696** [comment]
> While snapshotter has the information about what latest snapshots are pushed by itself, it does not have the information about the full snapshots pushed by compactor which runs separately. So, in e2e test for compaction, if we want to check the latest snapshots through this endpoint after a compaction job, this endpoint provides stale data about full snapshot as it only have the info about full snapshots pushed by the snapshotter.

thanks for clarifying, now it make sense. I think it should be mentioned in PR description as it seems important point to me.

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by abdasgupta** [comment]
I updated the PR description @ishan16696

**Pull request merged**
