### PR TITLE
Updated compact subcommend to throw warning instead of error if revisions are already compacted

### PR DESCRIPTION
**Pull request by aaronfern**
**What this PR does / why we need it**:
Currently the compact subcommand raises a fatal warning if compaction stops for any reason. Updated this behaviour to throw a warning for a special case where compaction does not happen if revisions are already compacted.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Compaction job will now throw warning instead of error if revisions are already compacted
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @aaronfern for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by amshuman-kr — COMMENTED** [review]
Thanks for the fix @aaronfern! Are we sure if `ErrCompacted` is the only error that happens when there is nothing to compact?

How about the case where there are no delta snapshots at all?

**Comment by aaronfern** [comment]
> Are we sure if `ErrCompacted` is the only error that happens when there is nothing to compact?

Well, It's the only error I've encountered being thrown up when there is nothing to compact.
Looking at the defined errors, it seems likely to be the only one, but I can't say with certainty that it's the only one that happens.


> How about the case where there are no delta snapshots at all?

I did try out this case and it does not throw up an error, so nothing to explicitly handle here

**Review by amshuman-kr — APPROVED** [review]
Thanks for the clarification @aaronfern! /lgtm

**Review by shreyas-s-rao — APPROVED** [review]
@aaronfern Nice catch with the error as well as the log message. LGTM

**Review by abdasgupta — APPROVED** [review]
LGTM

**Comment by abdasgupta** [comment]
Is it rebased and pushed again after merge of test cases fix?

**Comment by shreyas-s-rao** [comment]
@abdasgupta Ah yes that's the issue. @aaronfern won't be able to rebase this for the next 10 days. I will raise another PR and cherry-pick his change in that.

**Comment by abdasgupta** [comment]
> @abdasgupta Ah yes that's the issue. @aaronfern won't be able to rebase this for the next 10 days. I will raise another PR and cherry-pick his change in that.

Or Maybe, we can ask him over the phone if he has access to a laptop with git installed.

**Comment by shreyas-s-rao** [comment]
> Or Maybe, we can ask him over the phone if he has access to a laptop with git installed.

@abdasgupta I would suggest against doing that, since he's on vacation :)

**Comment by shreyas-s-rao** [comment]
Closing in favour of https://github.com/gardener/etcd-backup-restore/pull/358
/cc @aaronfern

**Pull request closed without merging**
