### PR TITLE
Fix --skip-hash-check not work

### PR DESCRIPTION
**Pull request by ThinkMo**
**What this PR does / why we need it**:
Fix bug flag --skip-hash-check not work
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @ThinkMo for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by ishan16696** [comment]
Thanks for the fix @ThinkMo

/second-opinion
@shreyas-s-rao @abdasgupta @amshuman-kr

**Review by amshuman-kr — APPROVED** [review]
Thanks @ThinkMo for the fix! /lgtm

**Review by shreyas-s-rao — APPROVED** [review]
Thanks @ThinkMo for your contribution. LGTM

**Comment by d-baranowski** [comment]
Can I run this image somehow? I can see it doesn't have a release tag yet

**Comment by shreyas-s-rao** [comment]
@d-baranowski We will be releasing `v0.13.0` shortly. Please subscribe to the repo to get notified about the release. In the meantime, you can use the image `eu.gcr.io/gardener-project/gardener/etcdbrctl:v0.13.0-dev-1638bef219bef7c5367875d78f8cd6a83ca5c539` that's been generated from the latest master commit.

**Pull request merged**
